### ISSUE TITLE
Crash on Startup 

### ISSUE THREAD

**Issue by AlphaKintari** [shadowfacts/Clipboard#7]
Clipboard error on Preinit:

[09:17:03] [Client thread/ERROR]: The following problems were captured during this phase
[09:17:03] [Client thread/ERROR]: Caught exception from clipboard
java.lang.RuntimeException: java.lang.ClassNotFoundException: net.shadowfacts.forgelin.KotlinAdapter

Full Log: [HERE](http://paste.ee/p/Q9SSc#)

Even with all but base mods disabled, Still get the same error:
Core Mods Log: [HERE](http://paste.ee/p/b7UpZ)

**Comment by shadowfacts** [comment]
[Forgelin](https://minecraft.curseforge.com/projects/shadowfacts-forgelin) is required.

**Comment by AlphaKintari** [comment]
crap.  Sorry about that. When it came up that your ShadowMC lib was a dependency in Forge I didn't think to check for any others. ::facepalm::
