### ISSUE TITLE
Crash when attempting to place clipboard on ground

### ISSUE THREAD

**Issue by Hjaldar** [shadowfacts/Clipboard#9]
When shift-right-clicking a clipboard onto the ground there is a crash. Looks fairly easy to fix from the crash log, which is below.

Clipboard-1.10.2-1.1.0 (latest)
Forge 12.18.2.2125 (latest)

Crash log: [crash-2016-11-14_16.54.28-client.txt](https://github.com/shadowfacts/Clipboard/files/588688/crash-2016-11-14_16.54.28-client.txt)

**Comment by shadowfacts** [comment]
Fixed in [version 1.1.1](https://minecraft.curseforge.com/projects/clipboard/files/2357558) for MC 1.10.2 and [version 1.2.1](https://minecraft.curseforge.com/projects/clipboard/files/2357559) for MC 1.11.
